### ISSUE TITLE
User story - Write README 

### ISSUE THREAD

**Issue by elamont174** [stephendawsondev/GrimManor#24]
### Story

As a contributor, I will contribute to the README so that the objectives are clearly met.

### Acceptance Criteria (from template README)

🎃 Creative design that enhances user-experience
🎃 Project fits theme of Halloween
🎃 Responsive and accessible for different screen sizes
🎃 Project is well planned using Github Projects
🎃 Overall project focus is realistic and has a sense of completeness

### Tasks

- [x] Write the intro
- [x] Contribute to goal section - problem statement
- [x] Contribute to goal section - objectives; UI
- [x] Contribute to goal section - objectives; responsiveness
- [x] Contribute to goal section - objectives; planning through GitHub
- [x] Contribute to goal section - target audience
- [x] Contribute to goal section - benefits
- [x] Tech section - "provide information about the technology stack, dependencies, and any technical details related to the project."
- [x] Credits section

**Comment by elamont174** [comment]
PLEASE CAN EVERYONE PROOF READ THE README AND ADD TO IT WHERE APPROPRIATE. 
I can't comment on responsiveness or the tech section. 
Will the "planning through Github" criteria be covered by our project board? 
I still have NO idea what it means by benefits? Will I ask our facilitator? 
Please can everyone make sure that everything they have used has received a credit? I have done everything that I can find in the Slack channel but I imagine there will be some things missing!

We have all worked so hard :) let's make sure we have the appropriate documentation to reflect it!

**Comment by stephendawsondev** [comment]
@elamont174 You will need to push and open a PR for your Readme changes so that they can be viewed on `main`. You can either ask the facilitator or ask in the Hackathon Slack channel. 

If you push the most recent version, I can take a look at the tech parts you're unsure of and submit a pull request.
